// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManifets(arg1) {
  return window['go']['core']['Core']['AddManifets'](arg1);
}

export function Autorized() {
  return window['go']['core']['Core']['Autorized']();
}

export function ChangeListeningDb(arg1) {
  return window['go']['core']['Core']['ChangeListeningDb'](arg1);
}

export function CreateManifest(arg1, arg2) {
  return window['go']['core']['Core']['CreateManifest'](arg1, arg2);
}

export function CreateNewAccount(arg1, arg2) {
  return window['go']['core']['Core']['CreateNewAccount'](arg1, arg2);
}

export function DatabaseUpdateEventServer(arg1, arg2) {
  return window['go']['core']['Core']['DatabaseUpdateEventServer'](arg1, arg2);
}

export function DeleteManifest(arg1) {
  return window['go']['core']['Core']['DeleteManifest'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['core']['Core']['GetMessages'](arg1);
}

export function GetProfile() {
  return window['go']['core']['Core']['GetProfile']();
}

export function ManifestList() {
  return window['go']['core']['Core']['ManifestList']();
}

export function NewMessage(arg1, arg2) {
  return window['go']['core']['Core']['NewMessage'](arg1, arg2);
}

export function Nodes() {
  return window['go']['core']['Core']['Nodes']();
}

export function StartManager() {
  return window['go']['core']['Core']['StartManager']();
}

export function TrayExit() {
  return window['go']['core']['Core']['TrayExit']();
}

export function TrayReady() {
  return window['go']['core']['Core']['TrayReady']();
}
