// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manifest} from '../models';
import {context} from '../models';
import {models} from '../models';

export function AddManifets(arg1:string):Promise<void>;

export function Autorized():Promise<boolean>;

export function ChangeListeningDb(arg1:manifest.Manifest):Promise<void>;

export function CreateManifest(arg1:string,arg2:string):Promise<string>;

export function CreateNewAccount(arg1:string,arg2:string):Promise<void>;

export function DatabaseUpdateEventServer(arg1:context.Context,arg2:manifest.Manifest):Promise<void>;

export function DeleteManifest(arg1:manifest.Manifest):Promise<void>;

export function ExportManifest(arg1:manifest.Manifest):Promise<void>;

export function GetMessages(arg1:manifest.Manifest):Promise<Array<models.Message>>;

export function GetProfile():Promise<string>;

export function ManifestList():Promise<Array<manifest.Manifest>>;

export function NewMessage(arg1:manifest.Manifest,arg2:string):Promise<void>;

export function Nodes():Promise<number>;

export function StartManager():Promise<void>;

export function TrayExit():Promise<void>;

export function TrayReady():Promise<void>;
