// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manifest} from '../models';

export function AddManifets(arg1:string):Promise<void>;

export function DeleteManifest(arg1:manifest.Manifest):Promise<void>;

export function ManifestList():Promise<Array<manifest.Manifest>>;

export function StartManager(arg1:string):Promise<void>;
