// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManifets(arg1) {
  return window['go']['src']['DbManager']['AddManifets'](arg1);
}

export function ChangeListeningDb(arg1) {
  return window['go']['src']['DbManager']['ChangeListeningDb'](arg1);
}

export function DatabaseUpdateEventServer(arg1, arg2) {
  return window['go']['src']['DbManager']['DatabaseUpdateEventServer'](arg1, arg2);
}

export function DeleteManifest(arg1) {
  return window['go']['src']['DbManager']['DeleteManifest'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['src']['DbManager']['GetMessages'](arg1);
}

export function GetProfile() {
  return window['go']['src']['DbManager']['GetProfile']();
}

export function ManifestList() {
  return window['go']['src']['DbManager']['ManifestList']();
}

export function NewMessage(arg1, arg2) {
  return window['go']['src']['DbManager']['NewMessage'](arg1, arg2);
}

export function Nodes() {
  return window['go']['src']['DbManager']['Nodes']();
}

export function StartManager(arg1, arg2) {
  return window['go']['src']['DbManager']['StartManager'](arg1, arg2);
}
