// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManifets(arg1) {
  return window['go']['src']['DbManager']['AddManifets'](arg1);
}

export function DeleteManifest(arg1) {
  return window['go']['src']['DbManager']['DeleteManifest'](arg1);
}

export function ManifestList() {
  return window['go']['src']['DbManager']['ManifestList']();
}

export function StartManager(arg1) {
  return window['go']['src']['DbManager']['StartManager'](arg1);
}
