// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manifest} from '../models';

export function ExportManifest(arg1:manifest.Manifest):Promise<void>;

export function GetAddres():Promise<string>;

export function GetProfile():Promise<string>;

export function Init(arg1:string):Promise<void>;

export function StartApi():Promise<string>;

export function StartManager():Promise<void>;
