// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportManifest(arg1) {
  return window['go']['app']['App']['ExportManifest'](arg1);
}

export function GetAddres() {
  return window['go']['app']['App']['GetAddres']();
}

export function GetProfile() {
  return window['go']['app']['App']['GetProfile']();
}

export function Init(arg1) {
  return window['go']['app']['App']['Init'](arg1);
}

export function StartApi() {
  return window['go']['app']['App']['StartApi']();
}

export function StartManager() {
  return window['go']['app']['App']['StartManager']();
}
