name: App build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: wailsTest, platform: linux/amd64, os: ubuntu-latest},
          {name: wailsTest, platform: windows/amd64, os: windows-latest},
          {name: wailsTest, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update pkg
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get update
      - name: Install libayatana-appindicator3-dev on Linux
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get install gcc libgtk-3-dev xvfb libayatana-appindicator3-dev -y
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
      - name: Run Custom build on linux...
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99
          sudo xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          wails build