name: App build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: Rosa-Linux, platform: linux/amd64, os: ubuntu-latest},
          {name: Rosa-Windows, platform: windows/amd64, os: windows-latest},
          # {name: wailsTest, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update pkg
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get update
      - name: Install libayatana-appindicator3-dev on Linux
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get install gcc libgtk-3-dev xvfb libayatana-appindicator3-dev -y
      - name: Install Xvfb
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get install -y xvfb
      - name: Start Xvfb
        if: matrix.build.os == 'ubuntu-latest'
        run: Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
      - name: Set DISPLAY variable
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # release:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Create release
  #     uses: Roang-zero1/github-create-release-action@v3
  #     with:
  #       version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   - name: Upload release artifacts
  #     uses: Roang-zero1/github-upload-release-artifacts-action@v2
  #     with:
  #       args: "*/bin/ dist/shell/compiled.sh"
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
