name: App build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: wailsTest, platform: linux/amd64, os: ubuntu-latest},
          {name: wailsTest, platform: windows/amd64, os: windows-latest},
          {name: wailsTest, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Update pkg
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get update
      - name: Install libayatana-appindicator3-dev on Linux
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get install gcc libgtk-3-dev xvfb libayatana-appindicator3-dev -y
      - name: Install xorg
        if: matrix.build.os == 'ubuntu-latest'
        run: sudo apt-get install xorg
      - name: Start Xorg
        if: matrix.build.os == 'ubuntu-latest'
        run: Xorg :0 -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./Xorg.log -config /etc/X11/xorg.conf -configdir ./xorg.conf.d &
      - name: Set DISPLAY variable
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:0
          echo "DISPLAY=:0" >> $GITHUB_ENV
      
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}